### ISSUE TITLE
[Question] "error" promise

### ISSUE THREAD

**Issue by gpicchiarelli** [i80and/pledge-rs#6]
Will "error" promise be handled?

[man page pledge](https://man.openbsd.org/OpenBSD-6.5/pledge.2)
> error
>     Rather than killing the process upon violation, indicate error with ENOSYS

**Comment by delan** [comment]
Soon! [v0.3.1](https://github.com/i80and/pledge-rs/releases/tag/v0.3.1) still uses the old [OpenBSD 5.9+ interface](https://man.openbsd.org/OpenBSD-6.2/pledge.2) from before execpromises and the error promise were added, but v0.4.0 should address this with #7 and #9.

**Comment by delan** [comment]
[pledge = "0.4.0"](https://crates.io/crates/pledge/0.4.0) is out, hopefully it serves your needs well! Closing this for now.
